# Makefile for $(APP_NAME) (no IDE). Uses openFrameworks' make system.
# You can override OF_ROOT from environment; default points to ../../libs/openFrameworks
OF_ROOT ?= $(abspath $(CURDIR)/../../libs/openFrameworks)

PROJECT_NAME = $(APP_NAME)
PROJECT_ROOT = .

include $(OF_ROOT)/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk
